Crud
yosefHesham/Blog-IT pull request #2
Opened 2023-02-23 18:48 UTC by yosefHesham

### Data Processing and Models
---

- Add Model for likes
- Add Model for users
- Add Model For comments.
- Add Model for posts

2023-02-23 19:06 UTC, AnselemOdims requested changes
### Hi @yosefHesham , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-23 19:06 UTC, AnselemOdims commented on app/models/user.rb
> +  has_many :likes, foreign_key: 'user_id'
- [ ] Good job on this so far, but if we reference the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) you would notice that the user foreign key is referenced with author. So please kindly change the `user_id` to `author_id`

2023-02-23 19:06 UTC, AnselemOdims commented on app/models/post.rb
> +  end
- [ ] [OPTIONAL] Good job on this method, however we can go further by including a [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - `after_save`[Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - after_save to call this method anytime a post is saved to the database.

2023-02-23 19:06 UTC, AnselemOdims commented on app/models/like.rb
> +  belongs_to :user
- [ ] Please kindly ensure that this references the user class.

Hint:
`belongs_to :author, class_name: 'User'`

2023-02-23 19:06 UTC, AnselemOdims commented on app/models/comment.rb
> +  belongs_to :user
- [ ] Please kindly reference the above suggestion.

2023-02-24 13:14 UTC, Lizdev-05 approved these changes
Hi @yosefHesham, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] PR has a title and summary. ✔️
- [ ] No linter errors ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 13:15 UTC, merged